### ISSUE TITLE
Question - Utilize Cassandra rather than EventStore

### ISSUE THREAD

**Issue by stuartsaltzman** [pawelkaczor/akka-ddd#12]
Hi, 

Is it possible to utilize Cassandra rather than EventStore (geteventstore.com)? Additionally, would it be possible to incorporate PersistentView (or, its new name - Persistence Query)?

I am looking to implement a solution similar to your ddd-leaven-akka-v2 example, but was hoping to utilize Cassandra rather than EventStore. I do not know anything about EventStore, which is why I leaning towards Cassandra - is EventStore as mature as Cassandra and production ready?

Thanks!

**Comment by pawelkaczor** [comment]
See: https://github.com/pawelkaczor/akka-ddd/issues/9
EventStore itself is production ready, but EventStore projections are not (still in beta).

**Comment by pawelkaczor** [comment]
Duplicates https://github.com/pawelkaczor/akka-ddd/issues/9
