### ISSUE TITLE
[write-front] generic schema of successful response

### ISSUE THREAD

**Issue by ghost** [pawelkaczor/akka-ddd#2]
Hi Pavel, very good implementation indeed.
Maybe something that I missed but in the "CommandHandler" trait you return a command processed (thank you) message.

How do we return a custom response per for command ?

**Comment by pawelkaczor** [comment]
Thank you borag!
What should front-write return in response to command request is still an open question in akka-ddd project. It could be some kind of  correlationId to be used by the client to poll view side for updated data.
Generally this functionality is a broader topic that needs to be think thought. 

Since you are interested in this topic I will transform this `question` issue into normal 'feature request` issue.

**Comment by ghost** [comment]
Ok thanks alot, now I need to think about it :)

**Comment by albertolobrano** [comment]
I am also interested in this.   Right now i am not using the command handler from the framework but i have play framework that talks directly with the offices.  From the aggregate root i return an event that play can process.  Upon receiving the response from the AR i wait 1 sec and i pull the data from the view layer.  This is working for now but is not a solution that i can use in prod.    I think a correlation id will work  , in the api we can have something like return if(corr>= reqId) else wait.

**Comment by ahjohannessen** [comment]
You could introduce a concept of CommandResponse that has a correlationId with Ack(cid) and Nack(cid, de) where de is a DomainError trait.

**Comment by pawelkaczor** [comment]
I need to read this discussion:  [causation or correlation id?](https://groups.google.com/forum/#!topic/event-store/pvk2iEBgBtA)

**Comment by pawelkaczor** [comment]
correlationId and causationId meta attributes are now properly propagated. Example message flow:
1. Client creates CommandMessage (CM) providing command message id (CM id)
2. CM is processed and EventMessage (EM) is raised containing causation id equal to CM id (correlation id is propagated (if exists))
3. (saga) SagaManager adds correlation id to EM
4. (saga) Saga creates CM with causation id equal to EM id, correlation id is propagated

No need to return a correlation id back to the client in response to a command.
