### ISSUE TITLE
A single projection fails causes Projection to spam lots of db connection

### ISSUE THREAD

**Issue by hengkysucanda** [pawelkaczor/akka-ddd#25]
I deduced that it spams db connection because in my case using postgresql, it prints out 
"FATAL: remaining connection slots are reserved for non-replication superuser connections" after a projection fails. I cannot use any other client to connect to postgres afterwards hence i cannot fix the db inconsistencies manually.

**Comment by pawelkaczor** [comment]
Hint: the problem is related to [HikariCP](https://brettwooldridge.github.io/HikariCP/) that was integrated in this commit: https://github.com/pawelkaczor/akka-ddd/commit/4ebc0d459baabe02fb954040dbefdcc4180beeb7
