### ISSUE TITLE
saga manager is singleton or multiple instances at runtime?

### ISSUE THREAD

**Issue by coding4m** [pawelkaczor/akka-ddd#27]
hi
it seems like the saga manager or process manager is state sensitive, is there just a singleton or multiple instance when a saga manager running ?

**Comment by pawelkaczor** [comment]
Hi @coding4m . The saga manager is a singleton (per business process class) receptor that propagates events to appropriate saga office. To provide at-least-once-delivery guarantee it writes incoming events to an in-memory journal. What do you mean by "state sensitive"?

**Comment by pawelkaczor** [comment]
Let's continue discussion on the gitter channel: https://gitter.im/pawelkaczor/akka-ddd
