### ISSUE TITLE
Durable scheduler

### ISSUE THREAD

**Issue by pawelkaczor** [pawelkaczor/akka-ddd#3]
#### Motivation

Sagas (Process Managers) should be able to schedule timeout events (deadlines) to be notified when deadline comes.
#### Solution proposal

I came up with an idea of durable scheduler built on top of Eventstore. 
See initial concept **[here](https://github.com/pawelkaczor/akka-ddd/blob/master/project/diagrams/DurableScheduler.png)**.

**Comment by albertolobrano** [comment]
i am not sure this need to be part of the framework.  The business logic should contain this.  

what will be the use case ?

**Comment by pawelkaczor** [comment]
Timeouts are part of business process model (See: [BPMN-Timer](http://training-course-material.com/training/BPMN_2.0_Events_Types#Timer)) thus they must be supported by business process engine. 

Axon and NServiceBus frameworks (both providing Saga support) also support timeout events:
- http://docs.particular.net/nservicebus/sagas/
- http://www.axonframework.org/docs/2.4/sagas.html#d5e2006

**Comment by pawelkaczor** [comment]
Commonly, timeout events are used to ensure Saga reaches end state (eg. `failure`) when event that was expected to happen in the future does not happen.

**Comment by albertolobrano** [comment]
I see your point.  In our case akka provides already the infrastructure to set timeouts on an actor that's why i thought we may not need it.  But If we want to  make it explicit in the framework then i like your diagrams

**Comment by pawelkaczor** [comment]
Akka does not provide durable scheduler (Timeout message will not survive
system crash) . That's the reason we have this ticket :)

2015-03-28 9:09 GMT+01:00 Alberto Lobrano notifications@github.com:

**Comment by albertolobrano** [comment]
OMG you are right. I am used to think in terms of their views that i completely missed your point.

**Comment by pawelkaczor** [comment]
MVP (minimum viable product) implemented.
