### ISSUE TITLE
Tenant Id

### ISSUE THREAD

**Issue by albertolobrano** [pawelkaczor/akka-ddd#4]
Do you think the tenant id should be part of the metadata ?

**Comment by pawelkaczor** [comment]
Yes, I think so.

**Comment by AshleyAitken** [comment]
Is this about making akka-ddd multi-tenant (i.e. segregating different "clients" events etc.)?

**Comment by pawelkaczor** [comment]
I think akka-persistence, akka-sharding and Eventstore fit well into multi-tenant architecture. But this issue was just a question about tenant Id. @albertolobrano: if akka-ddd needs to provide some additional support for multi-tenancy please share your expectations by creating new ticket.

**Comment by pawelkaczor** [comment]
@AshleyAitken I forgot to say you are also welcome to create an issue for multi-tenancy support :)
