### ISSUE TITLE
Best way to manage the event sequence number for view-update-elastic modue

### ISSUE THREAD

**Issue by albertolobrano** [pawelkaczor/akka-ddd#5]
The view-update module uses the event sequence number provided by the event store to skip the messages already processed by the view itself.

In the view-update-mysql you store the event number in a separated table wrapped in a transaction so if something goes wrong the event number will not be persisted and the transaction  rolled back. 

I am thinking to do the same for the elasticsearch module and to create a document responsible to keep event sequence numbers.  The main difference though is that Elasticsearch does not support transactions and does not provide any rollback mechanism leaving us  with a potential inconsistency within the data if something goes wrong.     This is not an issue for the work i am doing but maybe we can think a solution to make this better.

**Comment by pawelkaczor** [comment]
Why not to store/update sequence number in the doc being inserted/updated?

**Comment by albertolobrano** [comment]
yes it make sense for now to handle this way. If special cases will come up we will change it.
