### ISSUE TITLE
Support to persist a sequence of events

### ISSUE THREAD

**Issue by albertolobrano** [pawelkaczor/akka-ddd#6]
do you think we should add support for this : 

/**
- Asynchronously persists `events` in specified order. This is equivalent to calling
- `persist[A](event: A)(handler: A => Unit)` multiple times with the same `handler`,
- except that `events` are persisted atomically with this method.
  *
- @param events events to be persisted
- @param handler handler for each persisted `events`
  */
  final def persist[A](events: immutable.Seq[A])(handler: A ⇒ Unit): Unit =
    events.foreach(persist(_)(handler))

There are cases where from a single command we may want to raise several events and be sure will be handled atomically

**Comment by pawelkaczor** [comment]
Yes: https://github.com/akka/akka/blob/master/akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala#L257

We may need to introduce Commit like this one: https://github.com/Product-Foundry/akka-cqrs/blob/master/core/src/main/scala/com/productfoundry/akka/cqrs/Commit.scala

**Comment by albertolobrano** [comment]
yes that would work.
