### ISSUE TITLE
Events versioning

### ISSUE THREAD

**Issue by albertolobrano** [pawelkaczor/akka-ddd#7]
What should we do when an event changes overtime ?  for example today i am raising an event productCreated(id,name)   in a month time i decide to add an extra field sku so my events will become productCreated(id,name,sku) .   Right now unless i did something wrong is not possible as the framework will complain big time when it tries to deserialize old objects. 

how would you solve this issue ?

**Comment by pawelkaczor** [comment]
See this discussion on akka-user group:
[Best practices using Akka Persistence with long-running projects?](https://groups.google.com/forum/#!searchin/akka-user/Best$20practices$20using$20Akka$20Persistence$20with$20long-running$20projects/akka-user/xNtxm8sLtO0/6FcJNbbgoY0J)

Axon supports event-upcasting in the following way: 
http://www.axonframework.org/docs/2.4/repositories-and-event-stores.html#event-upcasting

We could build something similar for akka-ddd.

**Comment by albertolobrano** [comment]
just found a video that talks about it. if you send me your email i will share it with you on DropBox.

**Comment by Chumper** [comment]
if it is online i would like to see it too, may you can share a link?
I really like the way axon implemented the upcasting, i would like to have it too for akka

**Comment by pawelkaczor** [comment]
Problem of [events schema evolution](http://doc.akka.io/docs/akka/current/scala/persistence-schema-evolution.html) is addressed by Akka Persistence since version 2.4.0.
