### ISSUE TITLE
[view-update] Support views that are fed from multiple event streams

### ISSUE THREAD

**Issue by ahjohannessen** [pawelkaczor/akka-ddd#8]
I wonder why you only support one by_category stream pr. view, i.e. one stream source pr. view. Is that intentional?

**Comment by ahjohannessen** [comment]
Furthermore, why are you using an auto generated primary key instead of using `viewId` and `lastEventNr`:

``` scala
  class ViewMetadata(tag: Tag) extends Table[ViewMetadataRecord](tag, ViewMetadata.TableName) {
    def id = column[Option[Long]]("ID", O.PrimaryKey, O.AutoInc)
    def viewId = column[String]("VIEW_ID", O.NotNull)
    def lastEventNr = column[Long]("LAST_EVENT_NR", O.NotNull)
    def * = (id, viewId, lastEventNr) <> (ViewMetadataRecord.tupled, ViewMetadataRecord.unapply)
  }
```

Would something like the compound primary key below not work as well?

``` scala
class A(tag: Tag) extends Table[(Int, Int)](tag, "a") {
  def k1 = column[Int]("k1")
  def k2 = column[Int]("k2")
  def * = (k1, k2)
  def pk = primaryKey("pk_a", (k1, k2))
  // compiles to SQL:
  //   alter table "a" add constraint "pk_a" primary key("k1","k2")
}
```

**Comment by ahjohannessen** [comment]
An additional question, what is the purpose with having many projections in the following:

```
vuConfig.projections.foreach(_.consume(eventMessage))
```

in `SqlViewHandler`. I can only see examples of using a single projection for an event->view in your ddd-leaven-akka.

**Comment by pawelkaczor** [comment]
> > I wonder why you only support one by_category stream pr. view, i.e. one stream source pr. view. Is that intentional?

Yes, why not? View represents "state" of an AggregateRoot on query-side.

**Comment by pawelkaczor** [comment]
> > what is the purpose with having many projections in the following:[...]  I can only see examples of using a single projection for an event->view in your ddd-leaven-akka.

Imagine you need to update/insert data in/to multiple tables when consuming an event. All updates must be performed in one transaction, of course. You could either implement one Projection that is responsible to perform all updates or split the work to multiple Projections (one Projection per table). You have a choice.

**Comment by pawelkaczor** [comment]
> > Furthermore, why are you using an auto generated primary key instead of using viewId and lastEventNr:

Why compound key? viewId should be enough? I don't remember reason for introducing autogenerated pk. I need to check this and possibly simplify.

**Comment by ahjohannessen** [comment]
> Yes, why not? View represents "state" of an AggregateRoot on query-side.

I see, so if one has, say, reporting screen needs from different parts of streams using your approach would do that via something like applicative or monadic joins (in Slick terms) across different views.

**Comment by pawelkaczor** [comment]
You can still serve data to your complex report from one table. But then reporting data needs to be maintained by multiple views (eg. report1_sales_view, report1_shipping_view, report1_payment_view).

**Comment by pawelkaczor** [comment]
View != table in context of this discussion.

**Comment by ahjohannessen** [comment]
> Imagine you need to update/insert data in/to multiple tables when consuming an event. All updates must be performed in one transaction, of course. You could either implement one Projection that is responsible to perform all updates or split the work to multiple Projections (one Projection per table). You have a choice.

Ok, now I am a bit confused. What does view then mean if does not correspond with a specific table?

**Comment by ahjohannessen** [comment]
How do you reset pointers for a specific table then, is that possible? Like rebuilding some tables, but not all of them, that possibly have different views as sources?

**Comment by ahjohannessen** [comment]
> But then reporting data needs to be maintained by multiple views (eg. report1_sales_view, report1_shipping_view, report1_payment_view)

This is a bit close to what I meant with different sources, e.g.: (streamId -> long, view), producing data to a particular table. So in a way:

```
stream-1 -----|
              | ---- feeding --> report1_sales_view + metadata for keeping positions
stream-n -----|
```

then if something needs to be added and removed from that table, one could just drop data where `viewId == "report1_sales_view"` -- note: using my understanding of `viewId`.

How do you do that with your solution? Reset all `viewId`s that touch a particular reporting table, e.g. possibly affecting other reporting tables?

**Comment by pawelkaczor** [comment]
> > How do you reset pointers for a specific table then, is that possible?

If you have Projection per table than it should be easy to rebuild a table by running new view with single projection (generally speaking).

**Comment by pawelkaczor** [comment]
Ok, if I understand correctly, sometimes it would be useful to keep track of several entries in ViewMetadata table with the same viewId but different streamId. Currently this is not possible.

Change request accepted. Thank you.

**Comment by pawelkaczor** [comment]
@ahjohannessen feel free to contribute :)
